[db][xs]: Make sure new users are members of superuser (#82)
This is needed cause when DB exists but no users need to be created they need to be a member of superuser role.
```
ERROR:  must be member of role "dataexchange-sbx"
```